name: Deploy static content to Pages

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        uses: github/pages/deploy-pages@v1
